Issue 97
pybluez/pybluez pull request #244
Opened 2019-07-13 11:27 UTC by beadysea

Starting work to resolve #97 with improved documentation. So far I've started the process of writing restructured text files containing Sphinx directives. By using sphinx we can publish the projects documentation on [readthedocs.org
](https://readthedocs.org/)

Docs so far:
api.rst - (API Docs) Developers interface with autogenerated documentation from source code docstrings.
index.rst - Project homepage 

Checklist:
- [ ] Work on API docs
- [ ] Table of Contents
- [ ] Replace old docs with new docs
- [ ] Create user docs
- [ ] Create community docs?
- [ ] Set up for publishing (readthedocs/pythonhosted/gh-pages)

Maintainers and contributors are welcome to pitch in and help. I'll edit this post and comment here as work progresses.

2019-07-14 00:27 UTC, beadysea commented
Screenshots of sphinx html output from my local codebase using readthedocs template,

![index](https://user-images.githubusercontent.com/3253399/61177578-2dffd680-a5d1-11e9-8e85-bcd4f8f06204.png)
![install](https://user-images.githubusercontent.com/3253399/61177580-39530200-a5d1-11e9-801d-50855002561c.png)

text content on the following images are pulled directly from source code.
![api_common](https://user-images.githubusercontent.com/3253399/61177583-3fe17980-a5d1-11e9-9240-899598984620.png)
![api_common2](https://user-images.githubusercontent.com/3253399/61177585-453ec400-a5d1-11e9-95b5-11cb9b0a3881.png)

@rgov @karulis  I've read that it's possible to direct sphinx output to a gh-pages branch. The question is which direction do we want to go - readthedocs, gh-pages or both? 
I've no idea whether it's possible to publish on multiple sites, though I suspect it could be with some hacking of sphinx makefiles and/or config files.

2019-07-17 09:09 UTC, beadysea commented
@rgov @karulis I have managed to set up sphinx document generator and Travis CI to publish pages to <orgname>.gitHub.io.  See [example site](https://beadysea.github.io/)
The api documentation pulls descriptions from the codes docstrings. Travis CI will be set up to trigger a rebuild of the documentation if the commit is to master and the commit message contains publish_docs.

Is this the kind of thing you are looking for?

2019-07-18 12:52 UTC, ukBaz commented
FYI: To help with debugging Travis issues you might find the following of interest:
https://docs.travis-ci.com/user/running-build-in-debug-mode/

2019-07-18 13:01 UTC, beadysea commented
Thanks @ukBaz. I'll check it out. 'm trying to get test runs on python 2 and 3 then have Travis run sphinx to build docs and publish to gh-pages. Everything kind of works just not in the right sequence.

2019-07-18 15:22 UTC, ukBaz commented
Is there a reason that you are adding `jobs` to the `.travis.yml` file? Seems to make the file a lot more complex than it was before.
Would it be simpler to have the docs built in the `before_deploy` stage and then `deploy` will only run if the docs build successfully.
For reference:
https://docs.travis-ci.com/user/job-lifecycle/

2019-07-18 16:23 UTC, beadysea commented
Good point @ukBaz. My original intention was to only build the docs when necessary rather than on every commit. The conditional in the `stages` section only triggers a doc build when `publish_docs` is in a commit message.
Would we be able to do this in the `before deploy` section? If not then we would be redeploying the docs website on every commit.

2019-07-18 16:38 UTC, beadysea commented
For gh-page to deploy to pybluez/pybluez.github.io we need to set a `GH_PAGES_TOKEN` by generating a token 
See: https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
then adding the token the projects environment variables on TravisCI.

2019-07-18 16:42 UTC, ukBaz commented
It looks like conditionals are allowed in deploy:
https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
I do worry that a workflow that relies on something specific in the commit message might be a little error prone.
I personally like how it is done on "readthedocs", has a latest build plus the released versions.

2019-07-18 16:50 UTC, beadysea commented
Personally I'd prefer hosting on readthedocs and have them do the heavy lifting. The sphinx work I've done is all setup for it. Just needs someone to create a readthedocs account for the project.

2019-07-18 17:58 UTC, beadysea commented
Decided to take Travis back to original. We can add deployment if needed when a decision has been made re: readthedocs or gh-pages.

2019-07-18 18:21 UTC, beadysea commented
To help with review the main commits are

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/8c1a48841fdd3ed579a2307f1a5097cae4eb501b

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/07c0b6d4a9c23fb10eed1a9dce5328fad314eb40

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/717c48acc8072734908dc075028f86197f685e72

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/2969d1312935cedf345b27f9dadedffe31a396fe

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/7453e95c6ebc8fce268fb74c1893c453ec8828be

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/696eab5d3ff21baeb5d27bc0d374c3c405613af8

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/c688d0430b9aae877c757ee3ed9def2852ff504e

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/e0de17c1a6392fc2c0524b3f9bc5dc495537c3f8

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/a2556178914f9ff88126b308706b038073d2593c

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/e2b5756dc6e9aabb80c6912da72eae84cf588f0b

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/e67d37c91f2ea9d716282f1127103d9c17223ffa

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/c6b78ea84121f0e8c613dd7c41dbb7fb975354c1

- [ ] https://github.com/pybluez/pybluez/pull/244/commits/6a7698e36861c67271a50ede853dea5ae92e4309

The others are mostly minor changes or failed tests which have been fixed with later commits.

2019-07-18 21:20 UTC, rgov commented
There is already a readthedocs account. I have control over it. What would need to be done on my side?

2019-07-18 22:28 UTC, beadysea commented
@rgov you would need to import the pybluez project repo. If readthedocs (RTD) is linked to your GitHub account it should be straightforward. 
Once this PR is merged with master then RTD should automatically pick up the sphinx conf file and start building the docs. 
If we need to do any customisation we can do it by putting a readthedocs yml file on master similar to travis.

References:
https://docs.readthedocs.io/en/stable/intro/import-guide.html
https://docs.readthedocs.io/en/stable/config-file/index.html

2019-07-18 23:13 UTC, beadysea commented
Final check - ran sphinx make html
```Running Sphinx v2.1.2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

The HTML pages are in _build\html.

Build finished. The HTML pages are in _build/html. 
```

2019-07-19 00:54 UTC, rgov commented
Can you rebase (`git rebase -i`) to squash it into one or a few commits?

2019-07-19 00:55 UTC, rgov commented
Apologies, I hit the wrong button.

2019-07-19 10:09 UTC, beadysea commented
I tried rebasing, not sure if I've done it correctly. Should I have force pushed? Sorry some of this is new to me.

2019-07-19 14:42 UTC, rgov commented
Thanks.

2019-07-19 14:55 UTC, rgov requested changes
Thanks for working on this. I've included some feedback from a preliminary read-over.

What are you thinking we should do with the legacy_docs folder? Can we move these over to Sphinx?

2019-07-19 14:55 UTC, rgov commented on .travis.yml
> +      - libbluetooth-dev
Please add a newline to the end of this file.

2019-07-19 14:55 UTC, rgov commented on bluetooth/__init__.py
> +
Could you expand on why you prefer this blank line at the end of the docstring?

2019-07-19 14:55 UTC, rgov commented on docs/user/install.rst
> +**Mac OS Dependencies**
Please use "macOS", which is how Apple writes it (today, anyway).

2019-07-19 14:55 UTC, rgov commented on docs/user/install.rst
> +- Python 2.3 or later
macOS ships with Python 2.7 and has for years, so I don't think it's necessary to specify this.

2019-07-19 14:55 UTC, rgov commented on docs/user/install.rst
> +Download a stable release, or bleeding edge if you fancy the risk.
This is nice but having to update this table might turn into a pain. Can we just link to the [releases](https://github.com/pybluez/pybluez/releases) page and the master tarball?

2019-07-19 14:55 UTC, rgov commented on docs/user/install.rst
> +- BlueZ libraries and header files
Is there a Debian package for this?

2019-07-19 14:55 UTC, rgov commented on docs/user/install.rst
> +- Microsoft Windows XP SP1 or Windows Vista/7/8/8.1
What about Windows 10? I thought some users got it to work. If it doesn't work, maybe we should explicitly say Windows 10 is unsupported, or just link to the issue about it.

2019-07-19 19:01 UTC, beadysea commented on bluetooth/__init__.py
> +
Sphinx throws a warning if there is no blank line and I think RTD will treat warnings as errors and stop the build of html pages. 

By default Sphinx looks for restructured text tags in source code docstrings. Having all those tags in the source docstring can make it difficult to read within the code. To relax those rules I enabled google and numpy styling. Both of those broadly follow PEP8. Even with those active sphinx still complains. 

In a way I think it is a good thing as it gives us the basis for developing PyBluez guidelines to documenting code.

References:
[Sphinx example of Numpy docstring](https://www.sphinx-doc.org/en/master/usage/extensions/example_numpy.html#example-numpy)
[Sphinx example of Google docstring](https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html)
[Example of restructured text docstring style (bottom of page)](https://thomas-cokelaer.info/tutorials/sphinx/docstring_python.html)
[PEP8](https://www.python.org/dev/peps/pep-0008/)
[PEP484](https://www.python.org/dev/peps/pep-0484/)
[numpydoc docstring guide](https://numpydoc.readthedocs.io/en/latest/format.html)

2019-07-19 19:31 UTC, beadysea commented on docs/user/install.rst
> +- Microsoft Windows XP SP1 or Windows Vista/7/8/8.1
I'm on Win 10 but I think pip pulled down pybluez-win10. Is that the same project? I'll have to uninstall and do more investigation myself. For docs I think we link to the issue. When I have time I'll run through install scenarios on my own machine and comment on the steps I took in the issue.

2019-07-19 19:33 UTC, beadysea commented on docs/user/install.rst
> +- BlueZ libraries and header files
Not sure. I took the dependencies info from https://pybluez.github.io/

2019-07-19 19:34 UTC, beadysea commented on docs/user/install.rst
> +Download a stable release, or bleeding edge if you fancy the risk.
Agreed, I'll update.

2019-07-19 19:58 UTC, beadysea commented on .travis.yml
> +      - libbluetooth-dev
I left the legacy_docs folder for reference to check the new docs against the old ones. Unfortunately we can't move them over to Sphinx. Sphinx takes restructured text (rst) as input and outputs html. 
I could copy the folder onto my local machine and then remove it from the repo but I think it best to leave them for the present time in case others want to help out.

2019-07-19 20:02 UTC, beadysea commented on .travis.yml
> +      - libbluetooth-dev
blank line added. Should I do all the changes, rebase and force push again?

2019-07-19 20:11 UTC, rgov commented
We can squash them again at the end, I just didn’t want a huge number of commits. 

Thanks for making the changes. I’ll do some more review. 

Have you looked at using pandoc to help convert the legacy docs to rst?

Sent from my iPhone

> On Jul 19, 2019, at 16:02, Bill Crawford <notifications@github.com> wrote:
> 
> @beadysea commented on this pull request.
> 
> In .travis.yml:
> 
> > @@ -33,4 +33,4 @@ addons:
>    apt:
>      packages:
>        - bluez
> -      - libbluetooth-dev
> +      - libbluetooth-dev
> blank line added. Should I do all the changes, rebase and force push again?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-07-19 22:04 UTC, rgov commented on docs/user/install.rst
> +- Microsoft Windows XP SP1 or Windows Vista/7/8/8.1
No I don't think that's the same project. It shouldn't be a separate PyPI listing. I can't figure out if this user has ever posted here.

2019-07-19 22:05 UTC, rgov commented on bluetooth/__init__.py
> +
Ok thanks.

2019-07-19 23:13 UTC, beadysea commented on docs/user/install.rst
> +- Microsoft Windows XP SP1 or Windows Vista/7/8/8.1
Just tried a fresh install with pip. It installed pybluez 0.22.  I then uninstalled and tried an install using source from repo. It installed fine. In a python shell I tried import bluetooth and it fell over with the message no module 'bluetooth._msbt'. Still to figure out why.
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32 and I'm using Visual Studio 2017 with windows SDK10 installed.
I've copied everything from my cmd shell and I'll prepare a gist to attach to issues.

2019-07-19 23:38 UTC, beadysea commented on docs/user/install.rst
> +- Microsoft Windows XP SP1 or Windows Vista/7/8/8.1
How does this sound for windows 10:
Note We are aware some users have experienced problems installing PyBluez on Windows 10. You are welcome help us and try installing PyBluez on Windows 10 and reporting new issues here (link to issues). Take time to read existing issues before creating a new one. If your issue already exists post a comment to the issue providing details. Please be aware that if you
choose do choose to install PyBluez on Windows 10, you do so at your own risk. 
For the present time PyBluez does not officially support Windows 10.

2019-07-19 23:47 UTC, beadysea commented on docs/user/install.rst
> +- Python 2.3 or later
Agreed. I'll remove.

2019-07-19 23:49 UTC, beadysea commented on docs/user/install.rst
> +**Mac OS Dependencies**
Agreed. I'll check other for any other refs to Mac OS an update them

2019-07-20 11:32 UTC, beadysea commented on docs/user/install.rst
> +- BlueZ libraries and header files
Yes, see links:
[python-dev](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python-dev)
[python3-dev](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python3-dev)
[python-distutils-extra](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python-distutils)

2019-07-20 12:56 UTC, beadysea commented
@rgov I used pandoc today and have the legacy docs in rst format. Sphinx is throwing up warnings mainly relating to bad formatting and it would take a lot of work to fix them. On the plus side I can now see what they are supposed to look like and I think it would be easier to replicate using the sphinx autodoc functions. You'll see the autodoc references in the api files during you review.

The good thing about autodoc is it is pulling documentation from source code. We fix missing documentation in the source code and the documents will update. I think this way so we end up with consistent documentation across the project.

2019-07-22 23:20 UTC, rgov commented on docs/user/install.rst
> +- BlueZ libraries and header files
I think it would be nice to write this like:

```rst
GNU/Linux Dependencies
~~~~~~~~~~~~~~~~~~~~~~

- Python 2.3 or newer
- The distutils package (included with most Python distributions)
- BlueZ libraries and header files

On Debian and Ubuntu, these packages can be installed with: `sudo apt install libbluetooth3 libbluetooth-dev python3 python-distutils-extra`.
```

I don't think we should encourage people to install Python 2.7 because it is reaching its end of life. And I'm not sure if `python3-dev` is needed.

2019-07-22 23:24 UTC, rgov commented
I've added the user **beadysea** to the project on Read the Docs. Could you take a look at updating the rST subheadings and then we can go ahead and merge this in?

Thanks for the dedication to working on this!

2019-07-23 15:33 UTC, beadysea commented on docs/user/install.rst
> +- BlueZ libraries and header files
Agreed. After a little reflection I'm thinking we use the following for semantic structure for document headings.
``` 
# with overline, for parts
* with overline, for chapters
=, for sections
-, for subsections
^, for subsubsections
“, for paragraphs ```

2019-07-23 16:35 UTC, beadysea commented
I've been doing more work (as yet unfinished) on the API docs but this will touch on all the docstrings in the bluetooth folder. Would it best issue a new pull request once we have merged this one?

2019-07-23 16:49 UTC, rgov commented
Yes we could split it into two pull requests. Are you comfortable with my merging this in now?

2019-07-23 17:01 UTC, beadysea commented on docs/user/install.rst
> +- BlueZ libraries and header files
Should I remove all references to python 2 thereby moving the project wholly over to python3? Perhaps say "While Pybluez is compatible with python 2 at present, we are no longer maintaining or developing for python 2"  Then remove all references to 2.x in dependencies and state python 3.x dependencies instead.

2019-07-23 17:35 UTC, beadysea commented
I'm happy to merge if you are. Then we can focus on getting read the docs working.

2019-07-23 18:17 UTC, merged

2019-07-23 18:17 UTC, rgov commented
Done. Thanks so much!

2019-07-23 18:24 UTC, rgov commented on docs/user/install.rst
> +- BlueZ libraries and header files
I think that makes sense to do at some point. You could file an issue to track it.