Update docstrings and api documentation.
pybluez/pybluez pull request #253
Opened 2019-07-24 18:40 UTC by beadysea

I've updated the docstrings for all of `bluetooth/bluez` and some others in the other bluetooth modules. Also set up sphinx autosummary templates to allow sphinx to generate stub files. All of the files under `docs/api/packages/` from modules down are autogenerated by sphinx, creating the file structure which readthedocs will build against. 

Tested with sphinx in nitpick mode with no errors so hopefully this should be painless at the readthedocs end.  

Key points for review:

- I commented out the `__doc__` sections in bluetooth __init__.py. Sphinx seems to be a bit adhoc in finding those references.  I think it has to do with imports, so if `from bluetooth import *` is in a file sphinx finds the __doc__, if a file just does `import Bluetooth` or `from bluetooth import btcommon` then __doc__ is not read.  Anyway I decided to just put the documentation in each separate file. Duplication I know but then I'd argue it saves a developer from hunting around the codebase looking for the documented spec.
- widcomm.py  I had to comment out line 107 to stop sphinx falling over. It looks to me that this line has been left in from some testing. If it needs to be there then I think we have to do: `if __name__ == __main__` etc to prevent sphinx trying to execute it.
- I chose to write the docstrings using numpy docstring style. It does have the downside that it takes up more lines, however it does produce a clean easy to read docstring in code and it renders it out very nicely for readthedocs.
- Some of the parameter or return types may be wrong. I took my best guess at them by digging around the codebase and trying to deduce their type. As mentioned I focussed on bluez first. If that is accurate then everything mostly becomes a copy over to the other modules.

Final point - I think this is the last huge commit. From now on it will just be adding or amending pages in docs, or docstring updates on the six source code files.

2019-07-29 18:29 UTC, rgov commented
Thank you for all the work you've put into this.

One thing I'd like to think more about is the first bullet, commenting out the docstrings. If we do this, it will also break using the built-in `help()` function and probably code completion hints in smart IDEs.

What can we do to make this better? Most projects don't have this problem, do they?

2019-07-29 19:24 UTC, beadysea commented
I'll try a local sphinx build with the init.py docstrings in again and see what happens.

2019-07-29 20:51 UTC, rgov commented
Do you know if there is a way to get Read the Docs to run the sphinx-apidoc generation manually? Then we can drop these from the repo. I'm concerned that if we update the documentation, we might forget to run the generation step, and the code and docs will diverge.

2019-07-29 22:12 UTC, beadysea commented
> Do you know if there is a way to get Read the Docs to run the sphinx-apidoc generation manually? Then we can drop these from the repo. I'm concerned that if we update the documentation, we might forget to run the generation step, and the code and docs will diverge.

I think my latest commit solves this. I pointed autosummary to build api pages in docs _build directory and set autosummary generate in conf.py. Tested locally with sphinx-build and html pages were generated with no errors.

2019-07-29 22:32 UTC, rgov commented
I see, the point of the docstring override like this is to provide a single documentation for different backend implementations.

The line `inquirer = WCInquirer ()` in widcomm.py would not be appropriate to hide behind `__name__ == '__main__'` because it is a global shared instance of WCInquirer that is used throughout module's functions.  What is the Sphinx error? It's unusual, because it is a pretty common pattern.

2019-07-29 22:49 UTC, beadysea commented
See sphinx document extract:
```
autodoc imports the modules to be documented. 
If any modules have side effects on import, these will be executed by autodoc when 
sphinx-build is run.  If you document scripts (as opposed to library modules), make 
sure their main routine is protected by a if __name__ == '__main__' condition.
```
With `inquirer = WCInquirer ()` in sphinx falls over because it tries to execute the statement.

https://try-rtd-l10n.readthedocs.io/ja/latest/usage/quickstart.html#autodoc

2019-07-29 22:53 UTC, rgov commented
Executing the statement isn't precisely the problem, it's that the `__init__` method does something (tries to use a C module that might not be available and/or connects to a local port).

Potentially we should rewrite the code so that nothing happens at `__init__` time? I'm not sure. Is there a global variable or environment variable or something that tells us Autodoc is running?

2019-07-30 01:04 UTC, rgov commented
Is any of the content here needed ? https://github.com/pybluez/pybluez/tree/wiki If not we can delete this branch.

2019-07-30 01:33 UTC, beadysea commented
I have a local copy of the wiki branch so it's safe to delete. If there is anything missing in the current docs (which I doubt) then we can fix.

2019-07-30 01:39 UTC, beadysea commented
I have decided to leave widcomm out of the auto generated docs until we figure out how to get sphinx to play nicely with the code in that module.

2019-07-30 03:14 UTC, rgov commented
That sounds reasonable.

2019-07-30 06:31 UTC, ukBaz commented
FYI: If you have module that is not available for import by sphinx then you can use mock:
http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports

2019-07-30 07:25 UTC, beadysea commented
Thanks @ukBaz, I've already applied mocks for _widcomm among others in conf.py

2019-07-30 15:03 UTC, rgov requested changes
Sorry for the nitpicks!

2019-07-30 15:03 UTC, rgov commented on bluetooth/__init__.py
> +    """Perform a bluetooth device discovery.
When referring to the Bluetooth protocol (as opposed to the `bluetooth` module), please capitalize it.

2019-07-30 15:03 UTC, rgov commented on bluetooth/__init__.py
> +        Each service class is represented by a Universal Unique Identifier (UUID). This function
"Universally"; or just drop the part that spells it out, I think UUIDs are widely known.

2019-07-30 15:03 UTC, rgov commented on bluetooth/__init__.py
> +        When sdp fails to stop advertising for some reason.
Capitalize "SDP".

2019-07-30 15:03 UTC, rgov commented on bluetooth/bluez.py
> +"""GNU/Linux implementation of Bluetooth."""
This is not actually an implementation of "Bluetooth", perhaps you mean "of the bluetooth module"?

2019-07-30 15:03 UTC, rgov commented on bluetooth/bluez.py
> +if sys.version_info.major < 3:
In a recent pull request we were advised to check for features and not version numbers. Can we turn this into a feature check?

```
try:
    import x
except ImportError:
    import y
```

or

```
import x
try:
    a = x.old
except ValueError:
    a = x.new
```

2019-07-30 15:03 UTC, rgov commented on bluetooth/bluez.py
> +import array
Wasn't this just removed in another pull request?

2019-07-30 15:03 UTC, rgov commented on bluetooth/bluez.py
> +        When a bluetooth hci error occurs.
Please capitalize HCI.

2019-07-30 15:03 UTC, rgov commented on bluetooth/bluez.py
> +    this method
Are we supposed to remove this period in the new comment style? I don't see it consistently done here. I would prefer the period.

2019-07-30 15:03 UTC, rgov commented on bluetooth/bluez.py
> +
Please remove whitespace at the ends of lines. Something like `sed -i '' 's/ *$//' file.py` will do it, I think.

2019-07-30 15:03 UTC, rgov commented on bluetooth/bluez.py
> +    The protocol must be one of : HCI, L2CAP, RFCOMM, or SCO. SCO sockets have not been
Please remove the colon.

2019-07-30 15:03 UTC, rgov commented on bluetooth/bluez.py
> +            The default is RFCOMM
Missing a period here.

2019-07-30 15:05 UTC, rgov commented
I'm still concerned about the doc duplication between `__init__.py` and `bluez.py`. It will be easy for these to diverge and then some contributor down the line will have to figure out which one is correct and might get it wrong. I will ask around to other Python communities how to handle this properly.

2019-07-30 15:52 UTC, beadysea commented on bluetooth/bluez.py
> +    this method
my mistake.

2019-07-30 18:04 UTC, beadysea commented on bluetooth/bluez.py
> +import array
You're correct. Not sure what has happened here.

2019-07-30 18:11 UTC, beadysea commented
I see your point about duplication. I'm going to have a rethink about how best to go about this.

2019-07-31 08:16 UTC, beadysea commented
I've closed this because, on reflection, I think it's the wrong approach to take. It would be much simpler to focus on documenting the API in bluetooth.__init__.py, providing a single authoritative reference.

2019-07-31 19:37 UTC, rgov commented
Alright. I hope you don't lose too much work and can reuse what you've done
to clean up the docstrings.

What do you think about making __init__.py declare an interface, with each
function just passing arguments through to the backend module? See my
StackOverflow link above, the second example.

On Wed, Jul 31, 2019 at 4:16 AM Bill Crawford <notifications@github.com>
wrote:

> I've closed this because, on reflection, I think it's the wrong approach
> to take. It would be much simpler to focus on documenting the API in
> bluetooth.*init*.py, providing a single authoritative reference.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/pybluez/pybluez/pull/253?email_source=notifications&email_token=AAA2RX4SPXKLOL5RSQHOXH3QCFC5VA5CNFSM4IGS367KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GPAAY#issuecomment-516747267>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAA2RX5WAK7YI4XS5LETPGDQCFC5VANCNFSM4IGS367A>
> .
>

2019-07-31 21:39 UTC, beadysea commented
My worry with that method is that if someone extends functionality in a backend module, wouldn't they need to remember to add it to__init__.py. On the other hand, I've been experimenting with adding .__doc__ elements and sphinx throw errors with some functions. I'm still trying to figure out why but suspect it's to do with sphinx not finding the function's definition. This may turn out to be a good side effect but I need to investigate further.

2019-08-01 00:24 UTC, rgov commented
Well, my feeling is that we would probably *want* this to be the case, having to update the interface in `__init__.py`. Then all the other backends need to be updated to specify that the functionality is not implemented.

2019-08-01 00:59 UTC, beadysea commented
I think that's why sphinx is throwing errors with the `__doc__` method. for example functions like `get_l2cap_options` aren't defined in msbt.py. There are also functions defined in msbt.py and macos.py that aren't defined in bluez.py. Thinking out loud I'm wondering about how we handle the BluetoothSocket and DeviceDiscoverer classes. I don't think we would want to define them in init.

2019-08-01 01:04 UTC, rgov commented
We should define them in those backends and have them raise NotImplementedError. The interface should be the same across platforms as much as we can.

2019-08-01 08:05 UTC, ukBaz commented
@rgov, to suggest an answer for your question you posted on StackOverflow, is it a Factory design pattern you are looking for?
More information at:
https://python-3-patterns-idioms-test.readthedocs.io/en/latest/Factory.html

Another suggestion is to look at the [gpiozero project](https://github.com/gpiozero/gpiozero). I always think it is a good reference as to what Pythonic documentation should look like.

2019-08-02 15:12 UTC, beadysea commented
Also here: https://realpython.com/factory-method-python/

2019-08-02 15:23 UTC, rgov commented
I would say it's related to the factory pattern but that is usually in
reference to object-oriented programming, and I am not sure that I see the
value in converting PyBluez to be more object-oriented at this point.

Think of the C standard library functions, like strcpy(). There is one
standard interface for how these functions work, but depending on your
operating system, those function implementations may be provided by glib
(Linux), libSystem (macOS), msvcrt (Windows), etc.

On Fri, Aug 2, 2019 at 11:12 AM Bill Crawford <notifications@github.com>
wrote:

> Also here: https://realpython.com/factory-method-python/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pybluez/pybluez/pull/253?email_source=notifications&email_token=AAA2RXYB7E2UKZB4RWN6ZNLQCRFEBA5CNFSM4IGS367KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3OA2MI#issuecomment-517737777>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAA2RX5UONPBN2GDJ2UDQCTQCRFEBANCNFSM4IGS367A>
> .
>

2019-08-10 17:08 UTC, beadysea commented
I'm still not happy with this. I think it's too messy so I'm going to abandon this PR and do things in smaller stages.

2019-08-10 17:08 UTC, closed without merging