Travis CI: Upgrade to Python 3.7
pybluez/pybluez pull request #254
Opened 2019-07-29 11:02 UTC by cclauss

2019-07-29 14:25 UTC, rgov commented
Thanks for this one (and all the other pull requests)!

Debian "jessie" is on 3.4 and "stretch" is on 3.5. Ubuntu "Xenial" is on 3.5, "Bionic" and "Cosmic" are 3.6. macOS is on 2.7 and has been for a while, I think.

Could we instead do: 2.7, 3.5, 3.6, 3.7? This should cover most users.

2019-07-29 14:57 UTC, rgov requested changes

2019-07-29 14:57 UTC, rgov commented on .travis.yml
> +maxtrix:
Probably `matrix`? Could you squash your changes? Thanks!

2019-07-29 15:40 UTC, rgov commented
What's happening with Bionic?

2019-07-29 17:09 UTC, cclauss commented
Do you have a sense for why all the __bionic__ tests are failing?

2019-07-29 17:19 UTC, cclauss commented
Could it be a gcc difference?

https://docs.travis-ci.com/user/reference/xenial gcc v5.4.0
https://docs.travis-ci.com/user/reference/bionic gcc v7.4.0

2019-07-29 18:06 UTC, rgov commented
It's that `libbluetooth` is not available on Bionic. Is it a package you need to install, `libbluetooth-dev`?

2019-07-30 01:02 UTC, rgov commented
I tried fixing this myself but ran into problems.

Personally, I am not a fan of Travis CI and I think that the container-based CI offered by CircleCI is superior. See also, https://github.com/pybluez/pybluez/issues/193 where Travis was also a problem.

2019-07-30 06:11 UTC, cclauss commented
I propose that we check this one in with the bionic tests in __allow_failures__ mode to encourage experimentation to fix those tests.  I do not object to CircleCI but it would still be of interest to know why the Travis tests do not pass.

2019-07-30 14:47 UTC, merged

2019-07-30 14:48 UTC, rgov commented
Thank you!