Drop references to python 2.6 and lower in docs
pybluez/pybluez pull request #262
Opened 2019-07-29 18:01 UTC by beadysea

In view of #261, this updates installation instructions and readme.

2019-07-29 18:05 UTC, rgov commented on docs/user/install.rst
> -For Python 2.6, 2.7, 3.0, 3.1, 3.2
I'm not a Windows guy, can we change this to `3.5+`? I don't know if we want to support these old versions of Python 3.

2019-07-29 18:26 UTC, hugovk reviewed
Some minor nits

2019-07-29 18:26 UTC, hugovk commented on docs/user/install.rst
> +For experimental Bluetooth Low Energy support(only for Linux platform -
```suggestion
For experimental Bluetooth Low Energy support (only for Linux platform -
```

2019-07-29 18:26 UTC, hugovk commented on docs/user/install.rst
> +`ble-dependencies <https://bitbucket.org/OscarAcena/pygattlib/src/45e04060881a20189412681f52d55ff5add9f388/DEPENDS?at=default>`
```suggestion
`ble-dependencies <https://bitbucket.org/OscarAcena/pygattlib/src/45e04060881a20189412681f52d55ff5add9f388/DEPENDS?at=default>`)
```

2019-07-29 19:10 UTC, beadysea commented on docs/user/install.rst
> -For Python 2.6, 2.7, 3.0, 3.1, 3.2
Should we also remove Windows XP?  There are people out there still running on it but I think its time to consider removing support for it considering Windows 7 reaches end of support in 2020.

2019-07-29 19:11 UTC, beadysea commented on docs/user/install.rst
> +For experimental Bluetooth Low Energy support(only for Linux platform -
Agreed.

2019-07-29 19:13 UTC, beadysea commented on docs/user/install.rst
> +`ble-dependencies <https://bitbucket.org/OscarAcena/pygattlib/src/45e04060881a20189412681f52d55ff5add9f388/DEPENDS?at=default>`
Thanks @hugovk. I'll batch your suggestions.

2019-07-29 20:41 UTC, rgov commented on docs/user/install.rst
> -For Python 2.6, 2.7, 3.0, 3.1, 3.2
Yes I think if you are running a version of Windows from 2001 you can figure out how to install an old version of PyBluez also.

2019-07-29 20:48 UTC, rgov requested changes

2019-07-29 20:48 UTC, rgov commented on README.md
> +Please refer to the [PyBluez Installation page](https://pybluez.readthedocs.io/en/latest/user/install.html) on our [Read the Docs site.](https://pybluez.readthedocs.io/)
I think this is creating a cyclical reference. The way I see it, Read the Docs is a nice hosted version of the documentation in the repo, but the real "source of truth" should be inside the repository.

For instance, if these install instructions are different for a specific branch, or if they are looking at a historical checkout of the source, pointing to the latest docs on RtD is not necessarily correct.

```markdown
Please refer to the [installation instructions](/docs/user/install.rst).
```

What do you think?

2019-07-29 21:00 UTC, beadysea commented on README.md
> +Please refer to the [PyBluez Installation page](https://pybluez.readthedocs.io/en/latest/user/install.html) on our [Read the Docs site.](https://pybluez.readthedocs.io/)
Yes I see your point. While updating install.rst should auto-update RtD, pointing to the internal file would save updating readme on every release.

2019-07-29 21:36 UTC, beadysea commented on README.md
> +Please refer to the [PyBluez Installation page](https://pybluez.readthedocs.io/en/latest/user/install.html) on our [Read the Docs site.](https://pybluez.readthedocs.io/)
Updated.

2019-07-29 22:22 UTC, beadysea commented on docs/user/install.rst
> -For Python 2.6, 2.7, 3.0, 3.1, 3.2
Removed XP, Vista and references to python below 3.5 for windows.

2019-07-29 22:25 UTC, beadysea commented
Might need to merge #253 before this one. Both change install.rst and this PR supersedes the earlier changes.

2019-08-12 17:52 UTC, rgov requested changes

2019-08-12 17:52 UTC, rgov commented on docs/install.rst
> +.. _master.zip: https://github.com/pybluez/pybluez/archive/master.zip
Can you please move these up closer to where they are used? Right below the table is fine. I like things to stay close to where they are used.

2019-08-12 17:52 UTC, rgov commented on README.md
> +Please refer to the [installation instructions](/docs/user/install.rst).
As part of this pull request, you renamed the file to remove the `user/` part.

2019-08-12 18:04 UTC, rgov approved these changes

2019-08-12 18:05 UTC, merged