Drop support for EOL Python 2.7
pybluez/pybluez pull request #295
Opened 2019-12-31 09:30 UTC by hugovk

For https://github.com/pybluez/pybluez/issues/266.

Also add `python_requires` to setup.py to help pip.

2019-12-31 09:32 UTC, hugovk commented
Passing CI build:

* https://github.com/hugovk/pybluez/commit/c3d16c101a3391da40ece9b52951444a3d7920c7/checks?check_suite_id=379576864

2019-12-31 10:32 UTC, cclauss commented on bluetooth/bluez.py
> +            print("found: %s - %s (class 0x%X, rssi %s)" % \
Backslash line termination is neither required inside parens nor desired according to PEP8.   These instances can be found via __flake8 . —sélect=E502__

2019-12-31 10:45 UTC, hugovk commented on bluetooth/bluez.py
> +            print("found: %s - %s (class 0x%X, rssi %s)" % \
There's quite a few non-failing flake8 warnings on the CI, I'd suggest fixing those in another PR.

2019-12-31 17:49 UTC, rgov requested changes
Thanks for this! I'd like to see this exercised on different platforms before we release it, but it looks pretty good.

2019-12-31 17:49 UTC, rgov commented on bluetooth/bluez.py
> +get_byte = int
Unless this is something that users are importing from this module, I'd be happy to remove uses of `get_byte` altogether.

2019-12-31 17:49 UTC, rgov commented on bluetooth/bluez.py
> +            print("found: %s (class 0x%X, rssi %s)" % \
Could you change this to use `.format` as well for consistency?

2020-01-02 20:10 UTC, hugovk commented on bluetooth/bluez.py
> +get_byte = int
Any idea how to find out if people are using it?

2020-01-02 20:17 UTC, rgov commented on bluetooth/bluez.py
> +get_byte = int
Unfortunately it's used in one of the examples: https://github.com/pybluez/pybluez/blob/master/examples/advanced/inquiry-with-rssi.py#L102

Python doesn't give us a great way to deprecate it. My preference would just be to remove it altogether and make a note in the CHANGELOG that it is no longer necessary.

2020-01-02 21:10 UTC, hugovk commented on bluetooth/bluez.py
> +            print("found: %s (class 0x%X, rssi %s)" % \
Done!

2020-01-02 21:15 UTC, rgov commented on bluetooth/bluez.py
> +get_byte = int
Filed #299.

2020-01-02 21:15 UTC, rgov approved these changes

2020-01-02 21:15 UTC, merged